[build.environment]
HUGO_VERSION = "0.135.0"
TZ = "Asia/Hebron"

[build]
publish = "public"
command = "hugo --gc --minify"


[[headers]]
for = "/*"

[headers.values]
Content-Security-Policy = '''
style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
font-src 'self' https://fonts.gstatic.com;
img-src 'self' blob: data:;
media-src blob:;
frame-src blob:;
script-src 'self' https://unpkg.com;
connect-src 'self' blob: data: https://unpkg.com;
Cross-Origin-Opener-Policy: same-origin-allow-popups'''
