local_backend: true
backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img

i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: multiple_folders

  # Required - a list of locales to show in the editor UI
  locales: [en, ar]

  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: ar

collections:
  # - label: "Languages"
  #   name: "languages"
  #   folder: "content/languages"
  #   extension: "yml"
  #   format: "yml"
  #   create: false
  #   slug: "{{code}}"
  #   editor:
  #     preview: false
  #   fields:
  #     - { label: "Language", name: "language" , widget: string}
  #     - { label: "Country Code (for url)", name: "code" , widget: string}
  # - label: "Post"
  #   name: "post"
  #   folder: "_posts"
  #   slug: "{{year}}-{{month}}-{{day}}-{{title}}"
  #   create: true
  #   editor:
  #     preview: false
  #   fields:
  #     - label: Language
  #       name: language
  #       widget: relation
  #       collection: languages
  #       searchFields: ["language"]
  #       valueField: code
  #       displayFields: ["language"]
  #       default: "en"
  #     - { label: "Title", name: "title", widget: "string" }
  #     - { label: "Body", name: "body", widget: "markdown" }
  - name: 'theme'
    label: 'Theme'
    folder: 'content/en/theme'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      # - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      # - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      # - { label: 'Language', name: 'language' }